region= "eu-west-1"
instance_type= "m3.large"
environment="dev"
domain= "test.io"
devman-desiredcount=1
appstore-desiredcount= 1
admin-desiredcount = 1
docker-user=""
docker-pass=""
docker-email=""
zone_id="xxx"
